name: Typecheck, and Lint

on: [push]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: typecheck
              working-directory: ${{ github.workspace }}
              run: npm run typecheck
