name: Typecheck, and Test

on: [push]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install
              run: npm install
            - name: typecheck
              working-directory: ${{ github.workspace }}
              run: npm run typecheck
            - name: test
              run: npm run test
