name: Typecheck, and Lint

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    pre_job:
        # continue-on-error: true # Uncomment once integration is finished
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@master
              with:
                  github_token: ${{ github.token }}
                  paths_ignore: '["**/README.md", "**/docs/**"]'

    main:
        needs: pre_job
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: typecheck
              run: npm run typecheck
