name: Typecheck, and Lint

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    main:
        needs: pre_job
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: typecheck
              run: npm run typecheck
              with:
                  node-version: 14
